### ISSUE TITLE
compiling error

### ISSUE THREAD

**Issue by snow2flying** [Sherlock-Holo/lycoris#2]
got the following error when I tried to compile this project:

error: language item required, but not found: `eh_personality`
  |
  = note: this can occur when a binary crate with `#![no_std]` is compiled for a target where `eh_personality` is defined in the standard library
  = help: you may be able to compile for a target that doesn't need `eh_personality`, specify a target with `--target` or in `.cargo/config`

error: could not compile `lycoris-bpf` due to previous error
warning: build failed, waiting for other jobs to finish...

rust toolchain:
rustup -V
rustup 1.25.1 (bb60b1e89 2022-07-12)
info: This is the version for the rustup toolchain manager, not the rustc compiler.
info: The currently active `rustc` version is `rustc 1.66.0-nightly (9c56d9d6f 2022-09-29)`

**Comment by Sherlock-Holo** [comment]
did you run cargo build at the project root dir？if so, please try cd to the bpf dir and cargo build again
